CONSUMER_KEY = "INSERT YOUR CONSUMER KEY HERE"
CONSUMER_SECRET = "INSERT YOUR CONSUMER SECRET HERE"
ACCESS_TOKEN = "INSERT YOUR ACCESS TOKEN HERE"
ACCESS_TOKEN_SECRET = "INSERT YOUR ACCESS TOKEN SECRET HERE"
